name: Run Tests
on: [push, pull_request]
jobs:
  build:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U --upgrade-strategy=eager --pre -e .[testsuite]
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
      - name: Test with pytest
        run: |
          pytest -vv
